export default {
title: '石光',
    imgs: [
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/1.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/2.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/3.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/4.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/5.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/6.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/7.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/8.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/9.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/10.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/11.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/12.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/13.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/14.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/15.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/16.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/17.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/18.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/19.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/20.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/21.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/22.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/23.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/thing@stone/stone/shiguang/24.jpg' },
    ]
}