export default {
    title: '歌舞',
    imgs: [
        { type: 1, url: 'https://prugna.cn/video/26335c6f6d23ebbcc388376bc7548476.mp4' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(1).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(2).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(3).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(4).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(5).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(6).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(7).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(8).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(9).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(10).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(11).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(12).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(13).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(14).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(15).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(16).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(17).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(18).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(19).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(20).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(21).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(22).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(23).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(24).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(25).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/right@0.1/3/gewu/(26).jpg' },
    ]
}