export default {
    title: '缥香',
    imgs: [
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(1).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(2).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(3).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(4).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(5).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(6).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(7).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(8).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(9).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(10).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(11).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(12).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(13).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(14).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(15).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(16).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(17).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(18).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(19).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(20).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(21).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(22).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(23).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(24).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/piaoxiang/(25).jpg' },
    ]
}