export default {
    title: '踏古',
    imgs: [
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/1111.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/156.mp4' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (0).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (1).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (2).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (3).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (4).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (5).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (6).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (7).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (8).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6518 (9).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6612.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_6617.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_7907.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_7911.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_8894.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_8895.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/IMG_8898.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC01980.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC01981.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC02096.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC03381.jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC09674.jpg' },
        { type: 1, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC09713 (1).mp4' },
        { type: 1, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/tagu/LRG_DSC09713 (2).mp4' },
    ]
}