export default {
    title: 'Ask the moon',
    imgs: [
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(1).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(2).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(3).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(4).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(5).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(6).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(7).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(8).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(9).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(10).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(11).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(12).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(13).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(14).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(15).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(16).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(17).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(18).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(19).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(20).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(21).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(22).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(23).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(24).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(25).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(26).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(27).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(28).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(29).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(30).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(31).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(32).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(33).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(34).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(35).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(36).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(37).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(38).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(39).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(40).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(41).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(42).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(43).jpg' },
        { type: 0, url: 'https://cdn.jsdelivr.net/gh/plunjoin/jianjie-space@jie-space/wenyue/(44).jpg' },
    ]
}